SIM ?= verilator
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES = /home/ayanna/projects/riscv-cordic/src/imm_gen.sv
TOPLEVEL = imm_gen
MODULE = test_imm_gen

include $(shell cocotb-config --makefiles)/Makefile.sim