SIM ?= verilator
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES = /home/ayanna/projects/riscv-cordic/src/control.sv
TOPLEVEL = control
MODULE = test_control

include $(shell cocotb-config --makefiles)/Makefile.sim