SIM ?= verilator
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES = /home/ayanna/projects/riscv-cordic/src/regfile.sv
TOPLEVEL = regfile
MODULE = test_regfile

include $(shell cocotb-config --makefiles)/Makefile.sim